.github/workflows/codecoverage.yml

Created a .yml file to test code coverage via CodeCov

#2 Add code coverage

---

LICENSE

Changed license to Apache to allow patent use, but exclude trademark use.

Issue 03 license

---

.github/workflows/unit_tests.yml

Create a .yml file to run unit tests automatically across a range of python versions

#4 Add unittest workflow

---

usage.py

This is to be considered alpha. Defines the basic interface for our library.

#1 first draft of library classes and interface

---

docs/Makefile
docs/conf.py
docs/index.rst
docs/make.bat

Generated documentation with sphinx, this is being hosted on Read the Docs.

#12 Create docs directory and generate documentation on Read the Docs.

---

prototype.py

Prototype.py file reformatted (blank lines added) to address error thrown up by flake8 in unit test workflow

#17 Re-formatting file to enable unit tests to run

---

README.md
docs/index.rst
docs/quickstart.rst

Solved issue #12: I've set up automatic documentation with read the docs and sphinx, linked to it in the user readme and added a quickstart guide on read the docs.

Automatic documentation and added to user readme

---

docs/conf.py
usage.py

Edited variable names and whitespace in usage.py to comply with flake8 standards

Issue #04 Unittest usage.py file linting

---

.github/workflows/multiple_os.yml

Additional workflow to test compatibility with multiple operating systems

#4 Add workflow to test multiple os

---

README.md

Now the checks are passing, I've added the unit test and multiple os workflow badges to the README.

#4 Update README - unit test/multiple os badges

---

pkmodel/protocol.py
pkmodel/tests/test_protocol.py

Class has dose() method where the user can either have instantaneous dosing, or specify a dosing function. Passing scipy.integrate.odeint the function dose(func) works for continuous and discontinuous functions, e.g. where the dose is constantly input for half the time, then suddenly dropped to zero. 
Closes #16

Built the Protocol class

---

poetry.lock
pyproject.toml

Used Poetry to create a PKModel package and uploaded it to TestPyPi.
Uploading poetry.lock and pyproject.toml to repository

#29 PKModel package created, uploading poetry.lock and pyproject.toml file

---

requirements.txt
setup.py

Updating setup.py file to enable dependencies to be automatically downloaded when package is installed. Updating requirements.txt.

#29 updating setup.y file with dependencies, updated requirements.txt

---

README.md

Updating README to reflect correct installation steps

#34 Updating user README

---

pkmodel/model.py
pkmodel/tests/test_model.py

Implements Model Class with unittest. Passing unittests locally.

Issue #13 Build Model Class

---

pkmodel/model.py
pkmodel/protocol.py
pkmodel/tests/test_model.py
pkmodel/tests/test_protocol.py

Automated testing for the Protocol class along with a few updates to the Protocol class itself

#27 added tests for the Protocol class

---

README.md

Adding a (very) simple explanation of the model and updating the installation instructions

Update README 'About' and 'Installation' sections

---

README.md

Updating README to include a relevant example equation

#34 Update to include model equations

---

README.md
pyproject.toml
requirements.txt

Editing README to fix eq and link to requirements.txt

#34 Editing README for eq/requirements

---

README.md

Adding eq image and correcting typos

#34 Updating README 

---

README.md

Formatting of equation variable didn't read well, corrected this. Made about section more accurate.

#34 corrected formatting in equation variables and edited 'about'

---

pkmodel/solution.py
pkmodel/tests/test_solution.py

#15 extended ode system tests and solution input validation

---

pyproject.toml

Update toml to enable poetry rebuild

#64 update toml file with new version

---

pkmodel/solution.py

Issue 15 build solution class

---

docs/source/conf.py
docs/source/index.rst

Not sure if this will fix anything. I've only made a minor change to index.rst. The docs deploy fine using sphinx to do a local test.

Issue 75 docs

---

pyproject.toml

Updating version number to enable update of TestPyPi package - updating to incorporate validation updates

#64 update toml file for most recent version number
